---
- hosts: all
  become: true
  
  vars:
    rule_list:
      - { proto: tcp, from_port: 80, to_port: up, cidr_ip: 10.0.0.1/32 }
      - { proto: tcp, from_port: 443, to_port: 443, cidr_ip: 10.0.0.1/32 }
    ec2_group_region: us-east-1
    ec2_group_vpc: 'vpc-9834a3e2'
    ec2_group_description: 'launch-wizard-9 created 2020-04-12T09:02:28.822+05:30'
    ec2_group_name: launch-wizard-9

  vars_files:
    - vars/aws_config.yml

  tasks:
    - name: Change security group
      ec2_group:
        name: '{{ ec2_group_name }}'
        description: '{{ ec2_group_description }}'
        vpc_id: '{{ ec2_group_vpc }}'
        aws_access_key: '{{ access_key }}'
        aws_secret_key: '{{ secret_key }}'
        region: '{{ ec2_group_region }}'
        rules: '{{ rule_list }}'
