---
- hosts: all
  become: true
  tasks:
  - name: remove docker images
    command: docker rmi nidhishd/challenge
  - name: Login to Docker
    command: docker login
  - name: Pull docker images from DockerHub
    command: docker pull nidhishd/challenge
  - name: creating docker container using docker images
    command: docker run -d -it -p 8082:3000 --name challenge challenge
